In [1]:
! pip install ipywebrtc notebook



#point cloud rendering
#stable diffusion - text2img
#song 2 images - from splicing youtube
# lang-chain for switching songs kind of 
# automatic id tagging of libarry 

#speech analysis - for tempo, enunicaiton
# speech splitting from background 
#nbmerge nb1.ipynb nb2.ipynb > nb_all.ipynb
# take a song -> analyze it and then create a list of images
# https://github.com/tsaost/fast-stable-diffusion


#automagic lip syncing to music with a dancing cartoon 2024


# guess the time series properties of the music that DJS use to control light shows
# or have 100 lights controlled by 10 midi parameers

#animation time is controlled by beats 



#do analysis on the server of the song to see what the waveform of the person's voice needs to be to reach correct harmony - voice coach

#cant do that on the client because you have to separate the music from the vocals to make it less noisy -- 3-10 seconds w/ ai 


#visualize the waveform of both microphone 

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 260.7/260.7 kB 6.1 MB/s eta 0:00:00a 0:00:01


In [1]:
from ipywebrtc import AudioRecorder, CameraStream
import torchaudio
from IPython.display import Audio

In [2]:
camera = CameraStream(constraints={'audio': True,'video':False})
recorder = AudioRecorder(stream=camera)
recorder

AudioRecorder(audio=Audio(value=b'', format='webm'), stream=CameraStream(constraints={'audio': True, 'video': …

In [8]:
import os
#os.list_dir('/mnt/c/Users/17136/Downloads')

path = '/mnt/c/Users/17136/Downloads/'
file = 'output.mp3'
import librosa
# ! pip install audioread
# ! pip install soundfile
import soundfile as sf


In [14]:
#{yNone, sr=22050, S=None, n_fft=2048, hop_length=None, fmin=150.0, fmax=4000.0, threshold=0.1, win_length=None, window='hann', center=True, pad_mode='constant', ref=None
import audioread
#librosa.piptrack(path + file)
import numpy as np

path = '/mnt/c/Users/17136/Downloads/'
file = 'output.mp3'
output_file = './output.wav'

audio_path = path + file
y, sr = librosa.load(output_file)
audio_path = audio_path


    
    
#audio_path = audio_path
#data, sr = sf.read(audio_path)
print(y, sr)

frequencies, magnitudes = librosa.piptrack(y=y, sr=sr, S=None, n_fft=2048, hop_length=None, fmin=150.0, fmax=4000.0, threshold=0.1, win_length=None, window='hann', center=True, pad_mode='constant', ref=None)
#print(sr)  # Sample rate
# Calculate the pitch using librosa.piptrack


[-7.450581e-09  7.450581e-09  7.450581e-09 ...  2.818231e-02  4.677076e-02
  7.389563e-02] 22050


In [10]:
#!ffmpeg -i /mnt/c/Users/17136/Downloads/record.webm -b:a 192K -vn output.mp3
!ffmpeg -i /mnt/c/Users/17136/Downloads/record.webm -vn -acodec pcm_s16le -ar 44100 -ac 2 output.wav


ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enab

In [15]:
print(frequencies, magnitudes)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [2]:


# or run on GPU with INT8
# model = WhisperModel(model_size, device="cuda", compute_type="int8_float16")
# or run on CPU with INT8
# model = WhisperModel(model_size, device="cpu", compute_type="int8")
file_name = "Kygo - Firestone ft. Conrad Sewell (Official Video) [9Sc-ir2UwGU].mp3"
segments, info = model.transcribe(file_name , beam_size=5)

print("Detected language '%s' with probability %f" % (info.language, info.language_probability))

for segment in segments:
   print("[%.2fs -> %.2fs] %s" % (segment.start, segment.end, segment.text))

Detected language 'en' with probability 0.456299
[30.00s -> 40.00s]  I'm afraid, short of fire I'm the dark in need of light
[40.00s -> 49.00s]  When we touch, you inspire Feel the change in me tonight
[49.00s -> 57.00s]  So take me up, take me higher There's a wall not far from here
[57.00s -> 67.00s]  We can dive in desire But we can burn in love tonight
[67.00s -> 76.00s]  Our hearts are like firestorms But when they strike, we feel the love
[76.00s -> 85.00s]  Sparks will fly, they ignite our bones But when they strike, we light up the world
[85.00s -> 93.00s]  Our hearts are like firestorms But when they strike, we feel the love
[93.00s -> 102.00s]  Sparks will fly, they ignite our bones But when they strike, we light up the world
[102.00s -> 107.00s]  We light up the world
[115.00s -> 126.00s]  We light up the world
[126.00s -> 142.00s]  Firestorm
[143.00s -> 152.00s]  I'm for male, you're for white Perfect strangers in the night
[152.00s -> 162.00s]  Here we are, come together T

In [3]:
import yt_dlp


ydl_opts = {
    'format': 'bestaudio/best',
    'postprocessors': [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'mp3',
        'preferredquality': '192',
    }],
        'verbose': True,

}


fp = 'https://www.youtube.com/watch?v=9Sc-ir2UwGU&ab_channel=KygoOfficialVEVO'
with yt_dlp.YoutubeDL(ydl_opts) as ydl:
     print('wtfaasdfasdfa',ydl.download([fp]))

[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8 (No ANSI), error UTF-8 (No ANSI), screen UTF-8 (No ANSI)
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip) API
[debug] params: {'format': 'bestaudio/best', 'postprocessors': [{'key': 'FFmpegExtractAudio', 'preferredcodec': 'mp3', 'preferredquality': '192'}], 'verbose': True, 'compat_opts': set()}
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35 (OpenSSL 3.0.10 1 Aug 2023, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.18.0, brotli-None, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors


[youtube] Extracting URL: https://www.youtube.com/watch?v=9Sc-ir2UwGU&ab_channel=KygoOfficialVEVO
[youtube] 9Sc-ir2UwGU: Downloading webpage
[youtube] 9Sc-ir2UwGU: Downloading ios player API JSON
[youtube] 9Sc-ir2UwGU: Downloading android player API JSON
[youtube] 9Sc-ir2UwGU: Downloading m3u8 information


[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id


[info] 9Sc-ir2UwGU: Downloading 1 format(s): 251


[debug] Invoking http downloader on "https://rr3---sn-q4flrnss.googlevideo.com/videoplayback?expire=1691216049&ei=UZTNZOXZKLH82_gPgrc9&ip=73.77.43.211&id=o-AJvUGOxq7uLhkzwIJ2tSesrLAPdHNGHLKO4BxsymiiTF&itag=251&source=youtube&requiressl=yes&mh=WZ&mm=31%2C29&mn=sn-q4flrnss%2Csn-q4fl6nss&ms=au%2Crdu&mv=m&mvi=3&pl=16&initcwndbps=1865000&spc=UWF9f1dNT8oDi33Fm3mnZEGyl3eT2R8&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=3758379&dur=222.461&lmt=1655306999953790&mt=1691193934&fvip=2&keepalive=yes&fexp=24007246&beids=24350017&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhANH9gD8qxgmslaWtpwOSvQgpV3cU98jqD9XLd3BzEd8rAiEAtZQJ2OEABZN64zeOH_hPHLBZ3NhJwMEA5WnwohRjjRE%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAMfmGI2S6j-YVMinUp6uCqBo8RDBEMsMvG50AR3H1ZVGAiEAlaNaVSWhkZebauwRQkYynRNnaZlRvg2UuE_nEK6FY_0%3D"


[download] Destination: Kygo - Firestone ft. Conrad Sewell (Official Video) [9Sc-ir2UwGU].webm
[download] 100% of    3.58MiB in 00:00:00 at 16.55MiB/s  


[debug] ffmpeg command line: ffprobe -show_streams 'file:Kygo - Firestone ft. Conrad Sewell (Official Video) [9Sc-ir2UwGU].webm'


[ExtractAudio] Destination: Kygo - Firestone ft. Conrad Sewell (Official Video) [9Sc-ir2UwGU].mp3


[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Kygo - Firestone ft. Conrad Sewell (Official Video) [9Sc-ir2UwGU].webm' -vn -acodec libmp3lame -b:a 192.0k -movflags +faststart 'file:Kygo - Firestone ft. Conrad Sewell (Official Video) [9Sc-ir2UwGU].mp3'


Deleting original file Kygo - Firestone ft. Conrad Sewell (Official Video) [9Sc-ir2UwGU].webm (pass -k to keep)
wtfaasdfasdfa 0


ModuleNotFoundError: No module named 'beatnet'

In [4]:
from BeatNet.BeatNet import BeatNet

estimator = BeatNet(1, mode='realtime', inference_model='PF', plot=['beat_particles'], thread=False)

Output = estimator.process("./")

ImportError: cannot import name 'models' from partially initialized module 'madmom' (most likely due to a circular import) (/home/awahab/anaconda3/envs/shit/lib/python3.10/site-packages/madmom/__init__.py)

In [19]:
from spleeter.separator import Separator

# Using embedded configuration.
separator = Separator('spleeter:2stems')

In [ ]:
# Use audio loader explicitly for loading audio waveform :
from spleeter.audio.adapter import AudioAdapter

audio_loader = AudioAdapter.default()
sample_rate = 44100
waveform, _ = audio_loader.load(file_name, sample_rate=sample_rate)

# Perform the separation :
prediction = separator.separate(waveform)

In [1]:
import json
from faster_whisper import WhisperModel

model_size = "large-v2"

# Run on GPU with FP16
model = WhisperModel(model_size, device="cuda", compute_type="float16")

# or run on GPU with INT8
# model = WhisperModel(model_size, device="cuda", compute_type="int8_float16")
# or run on CPU with INT8
# model = WhisperModel(model_size, device="cpu", compute_type="int8")

def transcribe(fp):
    print(fp)
    info = model.transcribe(fp, beam_size=5)
    saveJSON(''.join(os.path.splitext(fp)[:-1]) + '.json', info)
    #lrcer.run(fp, target_lang='en') 
    #print("Detected language '%s' with probability %f" % (info.language, info.language_probability))
    #return 

def saveJSON(file_path, data):
    print(file_path)
    with open(file_path, "w") as json_file:
        json.dump(data, json_file)



In [2]:
import os

main_dir = './media'

def get_all_files_in_directory(directory):
    file_list = []
    for root, dirs, files in os.walk(directory):
        for file in files:
            file_list.append(os.path.join(root, file))
    return file_list

# Replace 'your_directory_path' with the path to the directory you want to search
directory_path = main_dir
all_files = get_all_files_in_directory(directory_path)

# Printing all the file paths found in the directory and its subdirectories
for file_path in all_files:
    #print(file_path)
    ext = os.path.splitext(file_path)[-1].lower()
    #print(ext)
    if ext == '.mp4' or ext == '.mp3': 
        transcribe(file_path)

./media/Billboard Hot 100 Singles Chart (24-June-2023) Mp3 320kbps [PMEDIA] ⭐️/001. Morgan Wallen - Last Night.mp3
./media/Billboard Hot 100 Singles Chart (24-June-2023) Mp3 320kbps [PMEDIA] ⭐️/001. Morgan Wallen - Last Night.json


TypeError: Object of type generator is not JSON serializable

In [1]:
from openlrc import LRCer

lrcer = LRCer()

# Single file
lrcer.run('audio.mp3', target_lang='zh-cn')  # Generate translated ./data/test.lrc with default translate prompt.


2023-08-05 16:46:18.938456: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
 [2023-08-05 16:46:20] INFO     [MainThread] Note: NumExpr detected 20 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
 [2023-08-05 16:46:20] INFO     [MainThread] NumExpr defaulting to 8 threads.
2023-08-05 16:46:21.153567: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:961] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-08-05 16:46:21.201643: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:961] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-08-05 16:46:21.201681: I tensor

ImportError: cannot import name 'get_terminal_size' from 'click.termui' (/home/awahab/anaconda3/envs/shit/lib/python3.10/site-packages/click/termui.py)

In [13]:
from basic_pitch.inference import predict_and_save

predict_and_save(
    ['./media/youtube/kygo.mp3'],
    'media/youtube/',
    True,
    True,
    True,
    True,
)


Predicting MIDI for media/youtube/kygo.mp3...


  Creating model output npz...
  💁‍♀️ Saved to media/youtube/kygo_basic_pitch.npz


  Creating midi...
  💅 Saved to media/youtube/kygo_basic_pitch.mid


  Creating midi sonification...
  🎧 Saved to media/youtube/kygo_basic_pitch.wav


  Creating note events...
  🌸 Saved to media/youtube/kygo_basic_pitch.csv


In [16]:
with open('/home/awahab/llm-testing/media/youtube/kygo_basic_pitch.csv') as f:
    for line in f:
        print(line)

start_time_s,end_time_s,pitch_midi,velocity,pitch_bend

236.18233922902496,236.28682902494333,69,58,1,1,1,1,1,1,1,1,1

233.08119138321996,233.23212108843538,57,57,1,1,1,1,1,1,1,1,1,1,1,1,1

232.66323219954648,232.75611201814058,69,43,1,1,1,1,1,1,1,1

232.16271927437643,232.24398911564626,69,49,0,1,1,1,1,1,1

232.16271927437643,232.5935723356009,57,43,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

232.06983945578233,232.16271927437643,69,29,1,1,1,1,1,1,0,0

232.06983945578233,232.16271927437643,57,68,1,1,1,1,1,1,1,1

232.0466195011338,232.15110929705216,71,42,1,1,1,1,1,1,1,1,1

231.81441995464854,231.94212970521542,61,48,1,1,1,1,1,1,1,1,1,1,1

231.80280997732427,232.06983945578233,57,48,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,-5,-5,-5,1

231.65188027210885,231.75637006802722,69,43,0,1,1,1,1,1,1,1,1

231.65188027210885,231.80280997732427,57,49,0,0,0,1,1,1,1,1,1,1,1,1,1

231.39646077097507,231.58222040816327,71,28,1,1,1,1,1,1,0,0,0,1,1,1,1,1,1,1

231.3964607709

In [21]:
# from visual_midi import Plotter
# from visual_midi import Preset
# from pretty_midi import PrettyMIDI

# # Loading a file on disk using PrettyMidi, and show
# pm = PrettyMIDI("/home/awahab/llm-testing/media/youtube/kygo_basic_pitch.mid")
# plotter = Plotter()
# plotter.show(pm, "./example-01.html")





from visual_midi import Plotter
from visual_midi import Preset
from pretty_midi import PrettyMIDI

# Using the `Preset` and `Plotter` to customize appearance (smaller plot)
pm = PrettyMIDI("/home/awahab/llm-testing/media/youtube/kygo_basic_pitch.mid")
preset = Preset(plot_width=850)
plotter = Plotter(preset, plot_max_length_bar=4)
plotter.show(pm, "/tmp/example-01.html")

AttributeError: unexpected attribute 'render_mode' to Label, possible attributes are angle, angle_units, background_fill_alpha, background_fill_color, border_line_alpha, border_line_cap, border_line_color, border_line_dash, border_line_dash_offset, border_line_join, border_line_width, coordinates, group, js_event_callbacks, js_property_callbacks, level, name, propagate_hover, subscribed_events, syncable, tags, text, text_align, text_alpha, text_baseline, text_color, text_font, text_font_size, text_font_style, text_line_height, text_outline_color, visible, x, x_offset, x_range_name, x_units, y, y_offset, y_range_name or y_units