In [1]:
import warnings
import pandas 
pandas.set_option('mode.use_inf_as_na', True)

warnings.filterwarnings("ignore")
warnings.simplefilter("ignore")

# This is required to catch warnings when the multiprocessing module is used
import os

os.environ["PYTHONWARNINGS"] = "ignore"
# import pertpy as pt
import scanpy as sc

import pertpy as pt
adata = pt.dt.kang_2018()

In [2]:
# adata.var_keys.

In [3]:
# result = []
# json = []
# for row in adata.obs.values:
#     result.append([item for kev, item in enumerate(row) ])
# for row in result: json.append({k: v for k, v in zip(adata.obs.columns.tolist(), row)})

# print(json)
#adata.var.highly_variable.keys

In [4]:
adata.var

name
index                       
AL627309.1        AL627309.1
RP11-206L10.2  RP11-206L10.2
RP11-206L10.9  RP11-206L10.9
FAM87B                FAM87B
LINC00115          LINC00115
...                      ...
C21orf58            C21orf58
PCNT                    PCNT
DIP2A                  DIP2A
S100B                  S100B
PRMT2                  PRMT2

[15706 rows x 1 columns]

In [68]:

sc.pp.log1p(adata)
sc.pp.highly_variable_genes(adata)

#hv_genes = filtered_keys = df[df['column_name'] == True].index.tolist()

#normal_genes = filtered_keys = df[df['column_name'] == False].index.tolist()

#print(hv_genes, normal_genes)
hv_genes = (list(adata.var[adata.var['highly_variable'] == True].index))
normal_genes = (list(adata.var_names))

hv_columns = [i for i,val in enumerate(normal_genes) if val in hv_genes]
#hv_genes

In [69]:
len(hv_columns)

659

In [70]:
#preprocess
#batchcontrol
#clustering
#cell type annotation
#embedding
#reverse transcriptome
#differential expression

#rna velocity -> predicts the future state 
#predict the probability of unseen perturbations
#test: first data set => output list of perturbations 
# take a 2nd dataset and get list of perturbations + their probability 


#representation learning (in particular, self-supervised, multi-view, and transfer learning
#https://registry.opendata.aws/tabula-muris/#usageexamples

#see what preprocessing is needed to get better accuracy

##load data

##import premade model => output list of predicted unseen perturbation

#write custom model. get better accuracy

In [71]:
sc.pp.calculate_qc_metrics(adata)
5

5

In [72]:
import requests
import time
from multiprocessing import cpu_count
from multiprocessing.pool import ThreadPool

def download_parallel(args):
    cpus = cpu_count()
    results = ThreadPool(cpus - 1).imap_unordered(download_url, args)
    for result in results:
        print('url:', result[0], 'time (s):', result[1])

In [73]:
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader

In [74]:
# gene_expressed = ["string1", "string2", "string3"]

    
# strings = np.array(gene_expressed)
# #adata.obs['genes_expressed'] = strings
# coordinates = []
cx = adata.X
cx = cx.tocoo()

# #delete non highly variable genes from matrix


# for i,j,v in zip(cx.row, cx.col, cx.data):
#     if i in hv_columns: coordinates += [[i,j,v]]
# for coord in coordinates:
#     coord[1] = adata.var_names[coord[1]]

#print(coordinates)

In [75]:
adata.obs
#batch removal - one patient at at time
#one cell_type at a time 
#index cell type
#index ctrl/stim
#

nCount_RNA  nFeature_RNA      tsne1      tsne2   condition  cluster        cell_type     replicate  nCount_SCT  \
index                                                                                                                              
AAACATACATTTCC-1      3017.0           877 -27.640373  14.966629     control        9  CD14+ Monocytes  patient_1016      1704.0   
AAACATACCAGAAA-1      2481.0           713 -27.493646  28.924885     control        9  CD14+ Monocytes  patient_1256      1614.0   
AAACATACCATGCA-1       703.0           337 -10.468194  -5.984389     control        3      CD4 T cells  patient_1488       908.0   
AAACATACCTCGCT-1      3420.0           850 -24.367997  20.429285     control        9  CD14+ Monocytes  patient_1256      1738.0   
AAACATACCTGGTA-1      3158.0          1111  27.952170  24.159738     control        4  Dendritic cells  patient_1039      1857.0   
...                      ...           ...        ...        ...         ...      ...              ...           ...         ...   
TTTGCATGCCTGAA-2      1033.0           468  18.268321   1.058202  stimulated        6      CD4 T cells  patient_1244      1128.0   
TTTGCATGCCTGTC-2      2116.0           819 -11.563067   2.574095  stimulated        4          B cells  patient_1256      1669.0   
TTTGCATGCTAAGC-2      1522.0           523  25.142392   6.603815  stimulated        6      CD4 T cells   patient_107      1422.0   
TTTGCATGGGACGA-2      1143.0           503  14.359657  10.965601  stimulated        6      CD4 T cells  patient_1488      1185.0   
TTTGCATGTCTTAC-2      1031.0           421  14.572118  -4.713942  stimulated        5      CD4 T cells  patient_1016      1144.0   

                  nFeature_SCT integrated_snn_res.0.4 seurat_clusters  geneExpressionCount  
index                                                                                       
AAACATACATTTCC-1           711                      1               1           234.670774  
AAACATACCAGAAA-1           662                      1               1           214.105606  
AAACATACCATGCA-1           337                      6               6            45.892522  
AAACATACCTCGCT-1           653                      1               1           226.106354  
AAACATACCTGGTA-1           928                     12              12           212.404950  
...                        ...                    ...             ...                  ...  
TTTGCATGCCTGAA-2           468                      2               2             0.000000  
TTTGCATGCCTGTC-2           799                      3               3             0.000000  
TTTGCATGCTAAGC-2           523                      0               0             0.000000  
TTTGCATGGGACGA-2           503                      0               0             0.000000  
TTTGCATGTCTTAC-2           419                      2               2             0.000000  

[24673 rows x 13 columns]

In [76]:
from collections import defaultdict
rowGeneExpression = defaultdict(int)
rowGeneExpression2 = defaultdict(dict)


import math
math.floor
df = adata.obs
end = 50 if True else -1
for column in hv_columns:
    for row_id in range(math.floor(float(df.shape[0])))[:end]:
        rowGeneExpression[row_id] += adata.X[row_id, column]
        #rowGeneExpression2[row_id][column] = adata.X[row_id, column]


In [77]:
df = adata.obs
dependent_variables =  [rowGeneExpression[row] for row in range(df.shape[0])]
df['geneExpressionCount'] = dependent_variables
numerical_values = df.select_dtypes(include=[int, float]).values.tolist()


In [78]:
import torch.optim as optim


criterion = torch.nn.CrossEntropyLoss()
#optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)


In [79]:
dependent_variables = [x / 50 for x in dependent_variables]

In [80]:
from torch import tensor

t_dep = tensor(dependent_variables) # pertrubations


In [81]:
t_indep = tensor(numerical_values, dtype=torch.float)
t_indep

tensor([[  3017.0000,    877.0000,    -27.6404,     14.9666,      9.0000,   1704.0000,    711.0000,    135.0695],
        [  2481.0000,    713.0000,    -27.4936,     28.9249,      9.0000,   1614.0000,    662.0000,    126.1152],
        [   703.0000,    337.0000,    -10.4682,     -5.9844,      3.0000,    908.0000,    337.0000,     26.5247],
        [  3420.0000,    850.0000,    -24.3680,     20.4293,      9.0000,   1738.0000,    653.0000,    130.6354],
        [  3158.0000,   1111.0000,     27.9522,     24.1597,      4.0000,   1857.0000,    928.0000,    108.0558],
        [  1869.0000,    635.0000,     -0.4702,    -25.3987,      5.0000,   1525.0000,    634.0000,     32.5236],
        [  1142.0000,    436.0000,    -15.9062,     20.0853,      9.0000,   1157.0000,    436.0000,     77.6361],
        ...,
        [   635.0000,    424.0000,     -6.6479,     -5.5475,      3.0000,    882.0000,    423.0000,      0.0000],
        [  1340.0000,    480.0000,      7.7202,     33.3402,      8.0000,  

In [82]:
t_indep.shape[1]

8

In [83]:

n_coeff = t_indep.shape[1]
coeffs = torch.rand(n_coeff)-0.5
coeffs

tensor([-0.0558, -0.2434,  0.1778,  0.0342,  0.4743,  0.0667,  0.3610,  0.3110])

In [84]:
def acc(coeffs): return (val_dep.bool()==(calc_preds(coeffs, val_indep)>0.1)).float().mean()
def calc_preds(coeffs, indeps): return (coeffs * indeps).sum(axis=1)
def calc_preds(coeffs, indeps): return torch.sigmoid((indeps*coeffs).sum(axis=1))

def calc_loss(coeffs, indeps, deps): return torch.abs(calc_preds(coeffs, indeps)-deps).mean()

In [85]:
preds = (t_indep*coeffs).sum(axis=1)
loss = torch.abs(preds-t_dep).mean()
loss = calc_loss(coeffs, t_indep, t_dep)

loss = torch.abs(preds-t_dep).mean()
loss

tensor(70.7701, dtype=torch.float64)

In [86]:
import torch, numpy as np, pandas as pd
np.set_printoptions(linewidth=140)
torch.set_printoptions(linewidth=140, sci_mode=False, edgeitems=7)
pd.set_option('display.width', 140)

In [87]:
vals,indices = t_indep.max(dim=0)
t_indep = t_indep / vals

In [88]:
t_indep*coeffs

tensor([[-0.0142, -0.0774, -0.1119,  0.0119,  0.4269,  0.0377,  0.1810,  0.2541],
        [-0.0117, -0.0630, -0.1113,  0.0230,  0.4269,  0.0357,  0.1685,  0.2372],
        [-0.0033, -0.0298, -0.0424, -0.0048,  0.1423,  0.0201,  0.0858,  0.0499],
        [-0.0161, -0.0751, -0.0986,  0.0163,  0.4269,  0.0385,  0.1662,  0.2457],
        [-0.0149, -0.0981,  0.1131,  0.0192,  0.1897,  0.0411,  0.2362,  0.2032],
        [-0.0088, -0.0561, -0.0019, -0.0202,  0.2372,  0.0337,  0.1614,  0.0612],
        [-0.0054, -0.0385, -0.0644,  0.0160,  0.4269,  0.0256,  0.1110,  0.1460],
        ...,
        [-0.0030, -0.0374, -0.0269, -0.0044,  0.1423,  0.0195,  0.1077,  0.0000],
        [-0.0063, -0.0424,  0.0313,  0.0265,  0.3795,  0.0293,  0.1222,  0.0000],
        [-0.0049, -0.0413,  0.0739,  0.0008,  0.2846,  0.0250,  0.1191,  0.0000],
        [-0.0100, -0.0723, -0.0468,  0.0020,  0.1897,  0.0369,  0.2034,  0.0000],
        [-0.0072, -0.0462,  0.1018,  0.0053,  0.2846,  0.0315,  0.1331,  0.0000],
   

In [89]:
t_indep = t_indep / vals

In [90]:
coeffs.requires_grad_()


tensor([-0.0558, -0.2434,  0.1778,  0.0342,  0.4743,  0.0667,  0.3610,  0.3110], requires_grad=True)

In [91]:
loss = calc_loss(coeffs, t_indep, t_dep)

loss.backward()

In [92]:
coeffs.grad

tensor([     0.0000,      0.0000,      0.0001,      0.0000,      0.0161,      0.0000,      0.0001,     -0.0000])

In [93]:
independent_variables = pd.DataFrame(numerical_values)

In [94]:
from fastai.data.transforms import RandomSplitter
trn_split,val_split=RandomSplitter(seed=42)(independent_variables)

In [95]:
trn_indep,val_indep = t_indep[trn_split],t_indep[val_split]
trn_dep,val_dep = t_dep[trn_split],t_dep[val_split]
#len(trn_indep),len(val_indep)

In [96]:
loss = calc_loss(coeffs, t_indep, t_dep)
loss.backward()
with torch.no_grad():
    coeffs.sub_(coeffs.grad * 0.1)
    coeffs.grad.zero_()
    print(calc_loss(coeffs, t_indep, t_dep))

tensor(0.5080, dtype=torch.float64)


In [97]:




def update_coeffs(coeffs, lr):
    coeffs.sub_(coeffs.grad * lr)
    coeffs.grad.zero_()

In [98]:
def one_epoch(coeffs, lr):
    loss = calc_loss(coeffs, trn_indep, trn_dep)
    loss.backward()
    with torch.no_grad(): update_coeffs(coeffs, lr)
    print(f"{loss:.3f}", end="; ")

In [99]:
def init_coeffs(): return (torch.rand(n_coeff)).requires_grad_()


torch.rand(n_coeff)

tensor([0.2168, 0.6564, 0.1267, 0.3521, 0.0668, 0.2042, 0.4393, 0.1597])

In [100]:
# def init_coeffs(): 
#     hiddens = [10, 10] # <-- set this to the size of each hidden layer you want_ 
#     sizes = [n_coeff] + hiddens + [1] 
#     n = len(sizes) 
#     layers = [(torch.rand(sizes[i], sizes[i+1])-0.3)/sizes[i+1]  for i in range(n-1)] 
#     consts = [(torch.rand(1)[0]-0.5)*0.1 for i in range(n-1)] 
#     for l in layers+consts:
#         l.requires_grad_() 
#     return layers,consts

# import torch.nn.functional as F 
# def calc_preds(coeffs, indeps): 
#     layers,consts = coeffs 
#     n = len(layers) 
#     res = indeps 
#     for i,l in enumerate(layers): 
#         res = res@l + consts[i] 
#         if i!=n-1: res = F.relu(res) 
#     return torch.sigmoid(res)

# def update_coeffs(coeffs, lr): 
#     layers, consts = coeffs 
#     for layer in layers+consts: 
#         layer.sub_(layer.grad * lr) 
#         layer.grad.zero_()



def train_model(epochs=30, lr=0.01):
    coeffs = init_coeffs()
    for i in range(epochs): one_epoch(coeffs, lr=lr)
    return coeffs

In [101]:
t_indep.shape

torch.Size([24673, 8])

In [102]:
coeffs = train_model(18, lr=0.2)

0.506; 0.506; 0.506; 0.506; 0.506; 0.506; 0.506; 0.506; 0.506; 0.506; 0.506; 0.505; 0.505; 0.505; 0.505; 0.505; 0.505; 0.505; 

In [103]:
coeffs

tensor([0.8913, 0.5993, 0.8357, 0.5418, 0.2899, 0.0137, 0.4507, 0.3668], requires_grad=True)

In [104]:
indep_cols = ['nCount_RNA' ,                
'nFeature_RNA'    ,             
'tsne1'     ,                 
'tsne2'  ,                   
'cluster'    ,                  
'nCount_SCT'   ,              
'nFeature_SCT',
'geneExpressionCount'
]    
def show_coeffs(): return dict(zip(indep_cols, coeffs.requires_grad_(False)))
show_coeffs()

{'nCount_RNA': tensor(0.8913),
 'nFeature_RNA': tensor(0.5993),
 'tsne1': tensor(0.8357),
 'tsne2': tensor(0.5418),
 'cluster': tensor(0.2899),
 'nCount_SCT': tensor(0.0137),
 'nFeature_SCT': tensor(0.4507),
 'geneExpressionCount': tensor(0.3668)}

In [105]:
def calc_preds(coeffs, indeps): return (indeps*coeffs).sum(axis=1)
#def calc_preds(coeffs, indeps): return torch.sigmoid(indeps@coeffs)

calc_preds(coeffs, t_indep)

tensor([0.0206, 0.0246, 0.0029, 0.0235, 0.0326, 0.0075, 0.0263,  ..., 0.0043, 0.0365, 0.0258, 0.0076, 0.0304, 0.0270, 0.0196])

In [106]:
coeffs

tensor([0.8913, 0.5993, 0.8357, 0.5418, 0.2899, 0.0137, 0.4507, 0.3668])

In [107]:
len([prob for prob in calc_preds(coeffs, t_indep) if prob > .02]) # should be 5000

14050

In [109]:

acc(coeffs) 
coeffs
##
# predictions = tf.nn.sigmoid(predictions)
# predictions = tf.where(predictions < 0.5, 0, 1)

# print('Predictions:\n', predictions.numpy())
# print('Labels:\n', label_batch)

# pass in a h5ad file and get back 
#Predictions:
# [0 0 0 0 0 1 1 1 0 0 0 1 0 1 0 0 1 0 1 0 0 0 0 0 1 1 0 1 1 1 0 0]
# Perturbations:
# [0 0 0 0 0 1 1 1 0 0 0 1 0 1 0 0 1 0 1 0 0 0 0 0 1 0 0 1 1 1 0 0]

tensor([0.8913, 0.5993, 0.8357, 0.5418, 0.2899, 0.0137, 0.4507, 0.3668])

In [45]:

# !pip install --quiet hyperopt
# !pip install --quiet "ray[tune]"
# !pip install --quiet scvi-colab
# from scvi_colab import install

# install()


# import ray
# import scanpy as sc
# import scvi
# from ray import tune
# from scvi import autotune
# model_cls = scvi.model.SCVI
# model_cls.setup_anndata(adata)
# scvi_tuner = autotune.ModelTuner(model_cls)


In [46]:
def benchmarkResults():
    pass

In [47]:
import scgen
adata.obs.rename({"label": "condition"}, axis=1, inplace=True)
adata.obs["condition"].replace({"ctrl": "control", "stim": "stimulated"}, inplace=True)




# https://genomebiology.biomedcentral.com/articles/10.1186/s13059-022-02605-1

# adata_t = adata[
#     ~(
#         (adata.obs["cell_type"] == "CD4 T cells")
#         & (adata.obs["condition"] == "stimulated")
#     )
# ].copy()

# cd4t_stim = adata[
#     (
#         (adata.obs["cell_type"] == "CD4 T cells")
#         & (adata.obs["condition"] == "stimulated")
#     )
# ].copy()








# scgen.SCGEN.setup_anndata(adata_t, batch_key="condition", labels_key="cell_type")


In [48]:
# model = scgen.SCGEN(adata_t, n_hidden=800, n_latent=100, n_layers=2)

In [49]:
# model.train(
#     max_epochs=1, batch_size=32, early_stopping=True, early_stopping_patience=25
# )

In [50]:
# adata_t.obsm["scgen"] = model.get_latent_representation()

In [51]:
# sc.pp.neighbors(adata_t, use_rep="scgen")
# sc.tl.umap(adata)

In [52]:
# adata_t

In [53]:
# pred, delta = model.predict(
#     ctrl_key="control", stim_key="stimulated", celltype_to_predict="CD4 T cells"
# )

# # we annotate the predicted cells to distinguish them later from ground truth cells.
# pred.obs["condition"] = "prediction"
# print(pred)

In [54]:
# pred.obs

In [55]:

# train = adata
# ctrl_adata = adata[
#     ((adata.obs["cell_type"] == "CD4 T cells") & (adata.obs["condition"] == "control"))
# ]
# stim_adata = train[((train.obs['cell_type'] == 'CD4T') & (train.obs['condition'] == 'stimulated'))]

# # concatenate pred, control and real CD4 T cells in to one object
# eval_adata = ctrl_adata.concatenate(cd4t_stim, pred)

In [56]:
# sc.tl.pca(eval_adata)
# sc.pl.pca(eval_adata, color="condition", frameon=False)

In [ ]:
# cd4t_adata = adata[adata.obs["cell_type"] == "CD4 T cells"]

In [ ]:
# sc.tl.rank_genes_groups(cd4t_adata, groupby="condition", method="wilcoxon")
# diff_genes = cd4t_adata.uns["rank_genes_groups"]["names"]["stimulated"]
# diff_genes

In [ ]:
# r2_value = model.reg_mean_plot(
#     eval_adata,
#     axis_keys={"x": "predicted stimulated", "y": "stimulated"},
#     gene_list=diff_genes[:10],
#     top_100_genes=diff_genes,
#     labels={"x": "predicted", "y": "ground truth"},
#     show=True,
#     legend=False,
# )

In [ ]:
# sc.pl.violin(eval_adata, keys="ISG15", groupby="condition")

In [ ]:
# import pertpy as pt
# import muon as mu
# import scanpy as sc

In [ ]:
# mdata = pt.dt.papalexi_2021()
# for col in mdata.obs: print(col)

In [ ]:
# sc.pp.normalize_total(mdata["rna"])
# sc.pp.log1p(mdata["rna"])
# sc.pp.highly_variable_genes(mdata["rna"], subset=True)

In [ ]:
# mu.prot.pp.clr(mdata["adt"])

In [ ]:
# sc.pp.pca(mdata["rna"])

In [ ]:
# We calculate neighbors with the cosine distance similarly to the original Seurat implementation
# sc.pp.neighbors(mdata["rna"], metric="cosine")

In [ ]:
# sc.tl.umap(mdata["rna"])

In [ ]:
# sc.pl.umap(mdata["rna"], color=["replicate", "Phase", "perturbation"])

In [ ]:
# ms = pt.tl.Mixscape()

# ms.perturbation_signature(
#     mdata["rna"],
#     pert_key="perturbation",
#     control="NT",
#     split_by="replicate",
#     n_neighbors=20,
# )

In [ ]:
# We create a copy of the object to recalculate the PCA.
# Alternatively we could replace the X of the RNA part of our MuData object with the `X_pert` layer.
# adata_pert = mdata["rna"].copy()
# adata_pert.X = adata_pert.layers["X_pert"]
# sc.pp.pca(adata_pert)
# sc.pp.neighbors(adata_pert, metric="cosine")
# sc.tl.umap(adata_pert)
# sc.pl.umap(adata_pert, color=["replicate", "Phase", "perturbation"])

In [ ]:
# ms.mixscape(adata=mdata["rna"], control="NT", labels="gene_target", layer="X_pert")

In [ ]:
# mdata["rna"].obs

In [ ]:
# pt.pl.ms.perturbscore(
#     adata=mdata["rna"], labels="gene_target", target_gene="IFNGR2", color="orange"
# )

In [ ]:
# sc.settings.set_figure_params(figsize=(10, 10))
# pt.pl.ms.violin(
#     adata=mdata["rna"],
#     target_gene_idents=["NT", "IFNGR2 NP", "IFNGR2 KO"],
#     groupby="mixscape_class",
# )

In [ ]:
# pt.pl.ms.heatmap(
#     adata=mdata["rna"],
#     labels="gene_target",
#     target_gene="IFNGR2",
#     layer="X_pert",
#     control="NT",
# )

In [ ]:
# mdata["adt"].obs["mixscape_class_global"] = mdata["rna"].obs["mixscape_class_global"]
# pt.pl.ms.violin(
#     adata=mdata["adt"],
#     target_gene_idents=["NT", "JAK2", "STAT1", "IFNGR1", "IFNGR2", "IRF1"],
#     keys="PDL1",
#     groupby="gene_target",
#     hue="mixscape_class_global",
# )

In [ ]:
# ms.lda(adata=mdata["rna"], labels="gene_target", layer="X_pert")

In [ ]:
# pt.pl.ms.lda(adata=mdata["rna"])
#https://zenodo.org/record/7058382
# folders = '/home/awahab/llm-testing/data_sets/'
# fp1 = 'SC3_v3_NextGem_DI_CRISPR_A549_5K_Multiplex_count_raw_feature_bc_matrix.h5'
# fp2 = 'SC3_v3_NextGem_DI_CRISPR_A549_5K_Multiplex_count_raw_molecule_info.h5'


# import h5py
# import anndata

# # Read the .h5 File
# def explore_h5py_group(group, indent=0):
#     """Recursively print the contents of an h5py group/dataset."""
#     print(group.data.name)
#     items = sorted(group.items())
#     for name, item in items:
#         if isinstance(item, h5py.Dataset):  # Check if item is a dataset
#             print("  " * indent + f"Dataset: {name} (Shape: {item.shape}, Dtype: {item.dtype})")
#         elif isinstance(item, h5py.Group):  # Check if item is a group
#             print("  " * indent + f"Group: {name}")
#             explore_h5py_group(item, indent + 1)  # Recursive call to explore subgroups

# # Open your HDF5 file
# with h5py.File(folders + fp1, 'r') as f:
#     explore_h5py_group(f)