In [130]:
import warnings
import pandas 
pandas.set_option('mode.use_inf_as_na', True)

warnings.filterwarnings("ignore")
warnings.simplefilter("ignore")

# This is required to catch warnings when the multiprocessing module is used
import os

os.environ["PYTHONWARNINGS"] = "ignore"
# import pertpy as pt
import scanpy as sc

import pertpy as pt
adata = pt.dt.kang_2018()

In [6]:
# adata.var_keys.

In [7]:
# result = []
# json = []
# for row in adata.obs.values:
#     result.append([item for kev, item in enumerate(row) ])
# for row in result: json.append({k: v for k, v in zip(adata.obs.columns.tolist(), row)})

# print(json)
#adata.var.highly_variable.keys

In [8]:
adata.var

name
index                       
AL627309.1        AL627309.1
RP11-206L10.2  RP11-206L10.2
RP11-206L10.9  RP11-206L10.9
FAM87B                FAM87B
LINC00115          LINC00115
...                      ...
C21orf58            C21orf58
PCNT                    PCNT
DIP2A                  DIP2A
S100B                  S100B
PRMT2                  PRMT2

[15706 rows x 1 columns]

In [77]:

sc.pp.log1p(adata)
sc.pp.highly_variable_genes(adata)

#hv_genes = filtered_keys = df[df['column_name'] == True].index.tolist()

#normal_genes = filtered_keys = df[df['column_name'] == False].index.tolist()

#print(hv_genes, normal_genes)
hv_genes = (list(adata.var[adata.var['highly_variable'] == True].index))
genes = (list(adata.var_names))

hv_columns = [i for i,val in enumerate(genes) if val in hv_genes]
#hv_genes

In [ ]:
len(hv_columns)

In [ ]:
highly_variable_columns = []


for key, gene in enumerate(normal_genes):
    if gene in hv_genes:
        highly_variable_columns += key

In [ ]:
highly_variable_columns
print(hv_genes, normal_genes)

In [ ]:
#preprocess
#batchcontrol
adata

In [ ]:
#clustering
#cell type annotation
#embedding
#reverse transcriptome
#differential expression

#rna velocity -> predicts the future state 
#predict the probability of unseen perturbations
#test: first data set => output list of perturbations 
# take a 2nd dataset and get list of perturbations + their probability 


#representation learning (in particular, self-supervised, multi-view, and transfer learning
#https://registry.opendata.aws/tabula-muris/#usageexamples

#see what preprocessing is needed to get better accuracy

##load data

##import premade model => output list of predicted unseen perturbation

#write custom model. get better accuracy

In [11]:
sc.pp.calculate_qc_metrics(adata)
5

5

In [12]:
import requests
import time
from multiprocessing import cpu_count
from multiprocessing.pool import ThreadPool

def download_parallel(args):
    cpus = cpu_count()
    results = ThreadPool(cpus - 1).imap_unordered(download_url, args)
    for result in results:
        print('url:', result[0], 'time (s):', result[1])

In [13]:
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader

In [52]:
# gene_expressed = ["string1", "string2", "string3"]

    
# strings = np.array(gene_expressed)
# #adata.obs['genes_expressed'] = strings
# coordinates = []
cx = adata.X
cx = cx.tocoo()

# #delete non highly variable genes from matrix


# for i,j,v in zip(cx.row, cx.col, cx.data):
#     if i in hv_columns: coordinates += [[i,j,v]]
# for coord in coordinates:
#     coord[1] = adata.var_names[coord[1]]

#print(coordinates)

In [78]:
# rowGeneExpression = {}

# for coordinate in coordinates:
#     row = coordinate[0]
#     gene = coordinate[1]
#     pvalue = coordinate[2]
#     if not row in rowGeneExpression:
#         rowGeneExpression[row] = 0
#     if gene in hv_genes: rowGeneExpression[row] += pvalue
# print(rowGeneExpression)

In [79]:
# hv_genes

In [80]:
len(hv_columns)

659

In [90]:
from collections import defaultdict
rowGeneExpression = defaultdict(int)

import math
math.floor
for column in hv_columns[:10]:
    for row_id in range(math.floor(float(df.shape[0]) / 2.)):
        rowGeneExpression[row_id] += adata.X[row_id, column]
        
rowGeneExpression

defaultdict(int,
            {0: 0.0,
             1: 0.526589035987854,
             2: 0.0,
             3: 0.526589035987854,
             4: 2.3243279457092285,
             5: 0.526589035987854,
             6: 0.0,
             7: 0.0,
             8: 0.869741678237915,
             9: 0.0,
             10: 0.0,
             11: 0.526589035987854,
             12: 0.0,
             13: 0.526589035987854,
             14: 1.579767107963562,
             15: 0.7412763237953186,
             16: 0.526589035987854,
             17: 0.0,
             18: 0.526589035987854,
             19: 0.0,
             20: 1.579767107963562,
             21: 0.0,
             22: 0.0,
             23: 0.0,
             24: 0.0,
             25: 0.0,
             26: 1.922919750213623,
             27: 0.0,
             28: 1.053178071975708,
             29: 0.0,
             30: 2.012312889099121,
             31: 1.053178071975708,
             32: 1.922919750213623,
             33: 0.0,
     

In [91]:
df = adata.obs
dependent_variables =  [rowGeneExpression[row] for row in range(df.shape[0])]
df['geneExpressionCount'] = dependent_variables
numerical_values = df.select_dtypes(include=[int, float]).values.tolist()


In [92]:
import torch.optim as optim


criterion = torch.nn.CrossEntropyLoss()
#optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)


In [93]:
from torch import tensor

t_dep = tensor(dependent_variables) # pertrubations


In [94]:
t_indep = tensor(numerical_values, dtype=torch.float)
t_indep

tensor([[  3017.0000,    877.0000,    -27.6404,     14.9666,      9.0000,   1704.0000,    711.0000,      0.0000],
        [  2481.0000,    713.0000,    -27.4936,     28.9249,      9.0000,   1614.0000,    662.0000,      0.5266],
        [   703.0000,    337.0000,    -10.4682,     -5.9844,      3.0000,    908.0000,    337.0000,      0.0000],
        [  3420.0000,    850.0000,    -24.3680,     20.4293,      9.0000,   1738.0000,    653.0000,      0.5266],
        [  3158.0000,   1111.0000,     27.9522,     24.1597,      4.0000,   1857.0000,    928.0000,      2.3243],
        [  1869.0000,    635.0000,     -0.4702,    -25.3987,      5.0000,   1525.0000,    634.0000,      0.5266],
        [  1142.0000,    436.0000,    -15.9062,     20.0853,      9.0000,   1157.0000,    436.0000,      0.0000],
        ...,
        [   635.0000,    424.0000,     -6.6479,     -5.5475,      3.0000,    882.0000,    423.0000,      0.0000],
        [  1340.0000,    480.0000,      7.7202,     33.3402,      8.0000,  

In [95]:
t_indep.shape[1]

8

In [96]:

n_coeff = t_indep.shape[1]
coeffs = torch.rand(n_coeff)-0.5
coeffs

tensor([-0.4256, -0.2000,  0.3981,  0.1186, -0.4704, -0.4822,  0.2264,  0.3808])

In [97]:
def acc(coeffs): return (val_dep.bool()==(calc_preds(coeffs, val_indep)>0.1)).float().mean()
def calc_preds(coeffs, indeps): return (indeps*coeffs).sum(axis=1)
def calc_loss(coeffs, indeps, deps): return torch.abs(calc_preds(coeffs, indeps)-deps).mean()

In [129]:
preds = (t_indep*coeffs).sum(axis=1)
loss = torch.abs(preds-t_dep).mean()
loss = calc_loss(coeffs, t_indep, t_dep)

loss = torch.abs(preds-t_dep).mean()
loss

tensor(0.2441, dtype=torch.float64)

In [99]:
import torch, numpy as np, pandas as pd
np.set_printoptions(linewidth=140)
torch.set_printoptions(linewidth=140, sci_mode=False, edgeitems=7)
pd.set_option('display.width', 140)

In [100]:
vals,indices = t_indep.max(dim=0)
t_indep = t_indep / vals

In [101]:
t_indep*coeffs

tensor([[-0.1087, -0.0636, -0.2505,  0.0413, -0.4233, -0.2728,  0.1135,  0.0000],
        [-0.0894, -0.0517, -0.2492,  0.0798, -0.4233, -0.2584,  0.1057,  0.0405],
        [-0.0253, -0.0244, -0.0949, -0.0165, -0.1411, -0.1454,  0.0538,  0.0000],
        [-0.1232, -0.0617, -0.2209,  0.0564, -0.4233, -0.2782,  0.1043,  0.0405],
        [-0.1137, -0.0806,  0.2534,  0.0667, -0.1881, -0.2973,  0.1482,  0.1787],
        [-0.0673, -0.0461, -0.0043, -0.0701, -0.2352, -0.2441,  0.1012,  0.0405],
        [-0.0411, -0.0316, -0.1442,  0.0554, -0.4233, -0.1852,  0.0696,  0.0000],
        ...,
        [-0.0229, -0.0308, -0.0603, -0.0153, -0.1411, -0.1412,  0.0675,  0.0000],
        [-0.0483, -0.0348,  0.0700,  0.0920, -0.3763, -0.2120,  0.0766,  0.0000],
        [-0.0372, -0.0339,  0.1656,  0.0029, -0.2822, -0.1806,  0.0747,  0.0000],
        [-0.0762, -0.0594, -0.1048,  0.0071, -0.1881, -0.2672,  0.1276,  0.0000],
        [-0.0548, -0.0379,  0.2279,  0.0182, -0.2822, -0.2277,  0.0835,  0.0000],
   

In [102]:
t_indep = t_indep / vals

In [103]:
coeffs.requires_grad_()


tensor([-0.4256, -0.2000,  0.3981,  0.1186, -0.4704, -0.4822,  0.2264,  0.3808], requires_grad=True)

In [104]:
loss = calc_loss(coeffs, t_indep, t_dep)

loss.backward()

In [105]:
coeffs.grad

tensor([    -0.0000,     -0.0001,     -0.0002,     -0.0001,     -0.0645,     -0.0001,     -0.0003,     -0.0093])

In [131]:
#dependent_variables

In [107]:
independent_variables = pd.DataFrame(numerical_values)

In [108]:
from fastai.data.transforms import RandomSplitter
trn_split,val_split=RandomSplitter(seed=42)(independent_variables)

In [109]:
trn_indep,val_indep = t_indep[trn_split],t_indep[val_split]
trn_dep,val_dep = t_dep[trn_split],t_dep[val_split]
#len(trn_indep),len(val_indep)

(19739, 4934)

In [110]:
def update_coeffs(coeffs, lr):
    coeffs.sub_(coeffs.grad * lr)
    coeffs.grad.zero_()

In [111]:
def one_epoch(coeffs, lr):
    loss = calc_loss(coeffs, trn_indep, trn_dep)
    loss.backward()
    with torch.no_grad(): update_coeffs(coeffs, lr)
    print(f"{loss:.3f}", end="; ")

In [112]:
def init_coeffs(): return (torch.rand(n_coeff)-0.5).requires_grad_()

In [113]:
def train_model(epochs=30, lr=0.01):
    coeffs = init_coeffs()
    for i in range(epochs): one_epoch(coeffs, lr=lr)
    return coeffs

In [114]:
coeffs = train_model(18, lr=0.2)

0.260; 0.259; 0.258; 0.257; 0.257; 0.256; 0.255; 0.254; 0.253; 0.252; 0.251; 0.251; 0.250; 0.249; 0.248; 0.247; 0.246; 0.246; 

In [115]:
indep_cols = ['nCount_RNA' ,                
'nFeature_RNA'    ,             
'tsne1'     ,                 
'tsne2'  ,                   
'cluster'    ,                  
'nCount_SCT'   ,              
'nFeature_SCT',
'geneExpressionCount'
]    
def show_coeffs(): return dict(zip(indep_cols, coeffs.requires_grad_(False)))
show_coeffs()

{'nCount_RNA': tensor(-0.2832),
 'nFeature_RNA': tensor(0.1566),
 'tsne1': tensor(-0.3719),
 'tsne2': tensor(-0.1477),
 'cluster': tensor(-0.2016),
 'nCount_SCT': tensor(-0.2953),
 'nFeature_SCT': tensor(-0.0597),
 'geneExpressionCount': tensor(-0.3067)}

In [127]:
def calc_preds(coeffs, indeps): return (indeps*coeffs).sum(axis=1)
def calc_preds(coeffs, indeps): return torch.sigmoid(indeps@coeffs)

calc_preds(coeffs, t_indep)

tensor([0.4965, 0.4946, 0.4991, 0.4946, 0.4889, 0.4964, 0.4958,  ..., 0.4989, 0.4949, 0.4961, 0.4985, 0.4956, 0.4961, 0.4969])

In [128]:
len([prob for prob in calc_preds(coeffs, t_indep) if prob > .5]) # should be 5000

239

In [117]:

acc(coeffs) + 1

##
# predictions = tf.nn.sigmoid(predictions)
# predictions = tf.where(predictions < 0.5, 0, 1)

# print('Predictions:\n', predictions.numpy())
# print('Labels:\n', label_batch)

# pass in a h5ad file and get back 
#Predictions:
# [0 0 0 0 0 1 1 1 0 0 0 1 0 1 0 0 1 0 1 0 0 0 0 0 1 1 0 1 1 1 0 0]
# Perturbations:
# [0 0 0 0 0 1 1 1 0 0 0 1 0 1 0 0 1 0 1 0 0 0 0 0 1 0 0 1 1 1 0 0]

tensor(1.7408)

In [118]:
def benchmarkResults():
    pass

In [119]:
import scgen
adata.obs.rename({"label": "condition"}, axis=1, inplace=True)
adata.obs["condition"].replace({"ctrl": "control", "stim": "stimulated"}, inplace=True)






# adata_t = adata[
#     ~(
#         (adata.obs["cell_type"] == "CD4 T cells")
#         & (adata.obs["condition"] == "stimulated")
#     )
# ].copy()

# cd4t_stim = adata[
#     (
#         (adata.obs["cell_type"] == "CD4 T cells")
#         & (adata.obs["condition"] == "stimulated")
#     )
# ].copy()








# scgen.SCGEN.setup_anndata(adata_t, batch_key="condition", labels_key="cell_type")


In [120]:
# model = scgen.SCGEN(adata_t, n_hidden=800, n_latent=100, n_layers=2)

In [121]:
# model.train(
#     max_epochs=1, batch_size=32, early_stopping=True, early_stopping_patience=25
# )

In [122]:
# adata_t.obsm["scgen"] = model.get_latent_representation()

In [123]:
# sc.pp.neighbors(adata_t, use_rep="scgen")
# sc.tl.umap(adata)

In [ ]:
# adata_t

In [ ]:
# pred, delta = model.predict(
#     ctrl_key="control", stim_key="stimulated", celltype_to_predict="CD4 T cells"
# )

# # we annotate the predicted cells to distinguish them later from ground truth cells.
# pred.obs["condition"] = "prediction"
# print(pred)

In [ ]:
# pred.obs

In [ ]:

# train = adata
# ctrl_adata = adata[
#     ((adata.obs["cell_type"] == "CD4 T cells") & (adata.obs["condition"] == "control"))
# ]
# stim_adata = train[((train.obs['cell_type'] == 'CD4T') & (train.obs['condition'] == 'stimulated'))]

# # concatenate pred, control and real CD4 T cells in to one object
# eval_adata = ctrl_adata.concatenate(cd4t_stim, pred)

In [ ]:
# sc.tl.pca(eval_adata)
# sc.pl.pca(eval_adata, color="condition", frameon=False)

In [ ]:
# cd4t_adata = adata[adata.obs["cell_type"] == "CD4 T cells"]

In [ ]:
# sc.tl.rank_genes_groups(cd4t_adata, groupby="condition", method="wilcoxon")
# diff_genes = cd4t_adata.uns["rank_genes_groups"]["names"]["stimulated"]
# diff_genes

In [ ]:
# r2_value = model.reg_mean_plot(
#     eval_adata,
#     axis_keys={"x": "predicted stimulated", "y": "stimulated"},
#     gene_list=diff_genes[:10],
#     top_100_genes=diff_genes,
#     labels={"x": "predicted", "y": "ground truth"},
#     show=True,
#     legend=False,
# )

In [ ]:
# sc.pl.violin(eval_adata, keys="ISG15", groupby="condition")

In [ ]:
# import pertpy as pt
# import muon as mu
# import scanpy as sc

In [ ]:
# mdata = pt.dt.papalexi_2021()
# for col in mdata.obs: print(col)

In [ ]:
# sc.pp.normalize_total(mdata["rna"])
# sc.pp.log1p(mdata["rna"])
# sc.pp.highly_variable_genes(mdata["rna"], subset=True)

In [ ]:
# mu.prot.pp.clr(mdata["adt"])

In [ ]:
# sc.pp.pca(mdata["rna"])

In [ ]:
# We calculate neighbors with the cosine distance similarly to the original Seurat implementation
# sc.pp.neighbors(mdata["rna"], metric="cosine")

In [ ]:
# sc.tl.umap(mdata["rna"])

In [ ]:
# sc.pl.umap(mdata["rna"], color=["replicate", "Phase", "perturbation"])

In [ ]:
# ms = pt.tl.Mixscape()

# ms.perturbation_signature(
#     mdata["rna"],
#     pert_key="perturbation",
#     control="NT",
#     split_by="replicate",
#     n_neighbors=20,
# )

In [ ]:
# We create a copy of the object to recalculate the PCA.
# Alternatively we could replace the X of the RNA part of our MuData object with the `X_pert` layer.
# adata_pert = mdata["rna"].copy()
# adata_pert.X = adata_pert.layers["X_pert"]
# sc.pp.pca(adata_pert)
# sc.pp.neighbors(adata_pert, metric="cosine")
# sc.tl.umap(adata_pert)
# sc.pl.umap(adata_pert, color=["replicate", "Phase", "perturbation"])

In [ ]:
# ms.mixscape(adata=mdata["rna"], control="NT", labels="gene_target", layer="X_pert")

In [ ]:
# mdata["rna"].obs

In [ ]:
# pt.pl.ms.perturbscore(
#     adata=mdata["rna"], labels="gene_target", target_gene="IFNGR2", color="orange"
# )

In [ ]:
# sc.settings.set_figure_params(figsize=(10, 10))
# pt.pl.ms.violin(
#     adata=mdata["rna"],
#     target_gene_idents=["NT", "IFNGR2 NP", "IFNGR2 KO"],
#     groupby="mixscape_class",
# )

In [ ]:
# pt.pl.ms.heatmap(
#     adata=mdata["rna"],
#     labels="gene_target",
#     target_gene="IFNGR2",
#     layer="X_pert",
#     control="NT",
# )

In [ ]:
# mdata["adt"].obs["mixscape_class_global"] = mdata["rna"].obs["mixscape_class_global"]
# pt.pl.ms.violin(
#     adata=mdata["adt"],
#     target_gene_idents=["NT", "JAK2", "STAT1", "IFNGR1", "IFNGR2", "IRF1"],
#     keys="PDL1",
#     groupby="gene_target",
#     hue="mixscape_class_global",
# )

In [ ]:
# ms.lda(adata=mdata["rna"], labels="gene_target", layer="X_pert")

In [ ]:
# pt.pl.ms.lda(adata=mdata["rna"])
#https://zenodo.org/record/7058382
# folders = '/home/awahab/llm-testing/data_sets/'
# fp1 = 'SC3_v3_NextGem_DI_CRISPR_A549_5K_Multiplex_count_raw_feature_bc_matrix.h5'
# fp2 = 'SC3_v3_NextGem_DI_CRISPR_A549_5K_Multiplex_count_raw_molecule_info.h5'


# import h5py
# import anndata

# # Read the .h5 File
# def explore_h5py_group(group, indent=0):
#     """Recursively print the contents of an h5py group/dataset."""
#     print(group.data.name)
#     items = sorted(group.items())
#     for name, item in items:
#         if isinstance(item, h5py.Dataset):  # Check if item is a dataset
#             print("  " * indent + f"Dataset: {name} (Shape: {item.shape}, Dtype: {item.dtype})")
#         elif isinstance(item, h5py.Group):  # Check if item is a group
#             print("  " * indent + f"Group: {name}")
#             explore_h5py_group(item, indent + 1)  # Recursive call to explore subgroups

# # Open your HDF5 file
# with h5py.File(folders + fp1, 'r') as f:
#     explore_h5py_group(f)